rate: 100
# Cartesian space tracking controller gains
# Kp_pos: [2000.0, 2000.0, 2000.0]
# Kd_pos: [150.0, 150.0, 150.0]
# Kp_att: [2000.0, 2000.0, 2000.0]
# Kd_att: [150.0, 150.0, 150.0]

# Kp_pos: [600.0, 600.0, 600.0]
# Kd_pos: [50.0, 50.0, 50.0]
# Kp_att: [600.0, 600.0, 600.0]
# Kd_att: [50.0, 50.0, 50.0]

Kp_pos: [100.0, 100.0, 100.0]
Kd_pos: [25.0, 25.0, 25.0]
Kp_att: [200.0, 200.0, 200.0]
Kd_att: [25.0, 25.0, 25.0]
# Direct force tracking controller gains
Kp_pos_f: [2,2,2]
Ki_pos_f: [0.5,0.5,0.5]

# IBVS controller gains
# # multitag
# # Kp_cam: [120.0, 120.0, 120.0, 120.0, 120.0, 120.0, 120.0, 120.0]
# # Kd_cam: [65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0]
# Kp_cam: [215.0, 215.0, 215.0, 215.0, 215.0, 215.0, 215.0, 215.0]
# Kd_cam: [105.0, 105.0, 105.0, 105.0, 105.0, 105.0, 105.0, 105.0]
# Kp_cam: [65.6, 65.6, 65.6, 65.6, 65.6, 65.6, 65.6, 65.6]
# Kd_cam: [75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0]
# Kp_cam: [400.0, 400.0, 400.0, 400.0, 400.0, 400.0, 400.0, 400.0]
# Kd_cam: [75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0, 75.0]

# only linear pos
# Kp_cam: [600.0, 600.0, 600.0, 600.0, 600.0, 600.0, 600.0, 600.0]
# Kd_cam: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0]

# Complete
# Kp_cam: [275.0, 450.0, 275.0, 450.0, 275.0, 450.0, 275.0, 450.0]
# Kd_cam: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0]
# Kp_cam: [600.0, 700.0, 600.0, 700.0, 600.0, 700.0, 600.0, 700.0]
# Kd_cam: [50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0, 50.0]

# Ki_cam: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


# Kp_cam: [400.0, 400.0, 400.0, 400.0, 400.0, 400.0, 400.0, 400.0]
# Kd_cam: [20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0, 20.0]
Kp_cam: [70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0]
Kd_cam: [15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0, 15.0]
Ki_cam: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
# Ki_cam: [30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0]
# Ki_cam: [5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0]



